DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_MATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 123456, 'MANUELA', 'JIMENEZ');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 456789, 'COSMO', 'SOSA');
